export { default as FontSize } from './FontSize.vue'
export { default as Label } from './Label.vue'
export { default as Color } from './Color.vue'
export { default as TextAlign } from './TextAlign.vue'
export { default as Padding } from './Padding.vue'
export { default as MaxLength } from './MaxLength.vue'
export { default as Options } from './Options.vue'
