export { default as Design } from './Design.vue'
export { default as FormDesign } from './FormDesign.vue'
export { default as Viewer } from './Viewer.vue'
export { default as DesignZone } from './DesignZone.vue'
export { default as ViewerZone } from './ViewerZone.vue'
export { default as DesignDraggable } from './DesignDraggable.vue'
